name: serverless_test

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_test
    environment:
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_admin -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_test: